name: Standard Checks (mypy, ruff, pytest)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.14"] # update when there's a new python version, 'stable' doesn't work apparently
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r devrequirements.txt
        pip install -r server/requirements.txt
    - name: Analysing the code with mypy, ruff and pytest
      run: |
        sh runchecks.sh
